/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Schedule;
import Business.ScheduleList;
import Business.Team;
import Business.TeamList;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private TeamList originalRank;
    private TeamList finalRank;
    private ScheduleList sl;
    private Boolean reset = false;
    
    public MainJFrame() {
        originalRank = new TeamList();
        finalRank = new TeamList();
        sl = new ScheduleList();
        readData();
        initComponents();
        btnReset.setEnabled(reset);
    }
    
    private void readData() {
        try ( BufferedReader br = new BufferedReader(new FileReader("EPL2020teams.csv"));) {
            String line = null;
            while ((line = br.readLine()) != null) {
                Team t = new Team(line);
                originalRank.addTeam(t);
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        try ( BufferedReader br = new BufferedReader(new FileReader("EPL2020data.csv"));) {
            String line = null;
            while ((line = br.readLine()) != null) {
                String[] fields = line.split(",");
                Team home = new Team();
                Team away = new Team();
                for (Team t : originalRank.getTeamList()) {
                    String s = t.getName();
                    if (s.equals(fields[3])) {
                        home = t;
                    }
                    if (s.equals(fields[4])) {
                        away = t;
                    }
                }
                update(home, away, fields[7]);
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        try ( BufferedReader br = new BufferedReader(new FileReader("EPL2020schd.csv"));) {
            String line = null;
            while ((line = br.readLine()) != null) {
                String[] fields = line.split(",");
                Team home = new Team();
                Team away = new Team();
                for (Team t : originalRank.getTeamList()) {
                    String s = t.getName();
                    if (s.equals(fields[0])) {
                        home = t;
                    }
                    if (s.equals(fields[1])) {
                        away = t;
                    }
                }
                Schedule s = new Schedule(fields[2], home, away);
                sl.addSchedule(s);
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
    
    private void update(Team home, Team away, String result) {
        if (home.getName() == null || away.getName() == null) {
            return;
        }
        int homeELO = home.getELO();
        int awayELO = away.getELO();
        float R1 = (float) Math.pow(10, homeELO / 400);
        float R2 = (float) Math.pow(10, awayELO / 400);
        float E1 = R1 / (R1 + R2);
        float E2 = R2 / (R1 + R2);
        if (result.equals("H")) {
            home.setELO((int) (homeELO + 16 * (1 - E1)));
            away.setELO((int) (awayELO + 16 * (0 - E2)));
            home.win();
            away.lose();
        } else if (result.equals("A")) {
            home.setELO((int) (homeELO + 16 * (0 - E1)));
            away.setELO((int) (awayELO + 16 * (1 - E2)));
            home.lose();
            away.win();
        } else {
            home.setELO((int) (homeELO + 16 * (0.5 - E1)));
            away.setELO((int) (awayELO + 16 * (0.5 - E2)));
            home.draw();
            away.draw();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane1 = new javax.swing.JSplitPane();
        leftJPanel = new javax.swing.JPanel();
        btnOriginal = new javax.swing.JButton();
        btnResult = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        rightJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnOriginal.setText("Ranking");
        btnOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOriginalActionPerformed(evt);
            }
        });

        btnResult.setText("Predict Result");
        btnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftJPanelLayout = new javax.swing.GroupLayout(leftJPanel);
        leftJPanel.setLayout(leftJPanelLayout);
        leftJPanelLayout.setHorizontalGroup(
            leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftJPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leftJPanelLayout.createSequentialGroup()
                        .addGroup(leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        leftJPanelLayout.setVerticalGroup(
            leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJPanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(btnOriginal)
                .addGap(119, 119, 119)
                .addComponent(btnResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(btnReset)
                .addContainerGap())
        );

        SplitPane1.setLeftComponent(leftJPanel);

        javax.swing.GroupLayout rightJPanelLayout = new javax.swing.GroupLayout(rightJPanel);
        rightJPanel.setLayout(rightJPanelLayout);
        rightJPanelLayout.setHorizontalGroup(
            rightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );
        rightJPanelLayout.setVerticalGroup(
            rightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        SplitPane1.setRightComponent(rightJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOriginalActionPerformed
        // TODO add your handling code here:
        OrigianlRankingJPanel origianlRankingJPanel = new OrigianlRankingJPanel(originalRank);
        SplitPane1.setRightComponent(origianlRankingJPanel);
    }//GEN-LAST:event_btnOriginalActionPerformed

    private void btnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultActionPerformed
        // TODO add your handling code here:
        PredictResultJPanel predictResultJPanel = new PredictResultJPanel(sl, btnReset.isEnabled(), btnReset);
        SplitPane1.setRightComponent(predictResultJPanel);
    }//GEN-LAST:event_btnResultActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        SplitPane1.setRightComponent(new JPanel());
        originalRank = new TeamList();
        sl = new ScheduleList();
        readData();
        originalRank.updateRanking();
        reset = false;
        btnReset.setEnabled(reset);
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitPane1;
    private javax.swing.JButton btnOriginal;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnResult;
    private javax.swing.JPanel leftJPanel;
    private javax.swing.JPanel rightJPanel;
    // End of variables declaration//GEN-END:variables
}
