/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Schedule;
import Business.ScheduleList;
import Business.Team;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class PredictResultJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PredictResultJPanel
     */
    private ScheduleList sl;
    private Boolean reset;
    private JButton btnReset;
    private Random rand = new Random();
    public PredictResultJPanel(ScheduleList sl, Boolean reset, JButton btnReset) {
        initComponents();
        btnAll.setEnabled(!reset);
        btnOnce.setEnabled(!reset);
        this.sl = sl;
        this.reset = reset;
        this.btnReset = btnReset;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel)tblSchedule.getModel();
        dtm.setRowCount(0);
        
        for(Schedule t : sl.getScheduleList()) {
            Object row[] = new Object[5];
            row[0] = t.getDate();
            row[1] = t.getHome().getName();
            row[2] = t.getAway().getName();
            row[3] = t.getHomeWinRate();
            row[4] = t.getResult();
            dtm.addRow(row);
        }
    }
    private void update(Team home, Team away, String result) {
        if (home.getName() == null || away.getName() == null) {
            return;
        }
        int homeELO = home.getELO();
        int awayELO = away.getELO();
        float R1 = (float) Math.pow(10, homeELO / 400);
        float R2 = (float) Math.pow(10, awayELO / 400);
        float E1 = R1 / (R1 + R2);
        float E2 = R2 / (R1 + R2);
        if (result.equals("H")) {
            home.setELO((int) (homeELO + 16 * (1 - E1)));
            away.setELO((int) (awayELO + 16 * (0 - E2)));
            home.win();
            away.lose();
        } else if (result.equals("A")) {
            home.setELO((int) (homeELO + 16 * (0 - E1)));
            away.setELO((int) (awayELO + 16 * (1 - E2)));
            home.lose();
            away.win();
        } else {
            home.setELO((int) (homeELO + 16 * (0.5 - E1)));
            away.setELO((int) (awayELO + 16 * (0.5 - E2)));
            home.draw();
            away.draw();
        }
    }
    
    private void runGame (Schedule s) {
        Team home = s.getHome();
        Team away = s.getAway();
        float winRate = (float) (100 / (1 + Math.pow(10, (away.getELO() - home.getELO()) / 400.0)));
        float drawPeriod = Math.abs(2 * winRate - 100) / 100; 
        int winValue = (int) (66 * winRate / 100 + 34 * winRate / 100 * drawPeriod);
        int drawValue = (int) (winValue + 34 * (1 - drawPeriod));
        int r = 1 + rand.nextInt(100);
        if (r > drawValue) {
            s.setResult("A");
        } else if (r > winValue) {
            s.setResult("D");
        } else {
            s.setResult("H");
        }
        update(home, away, s.getResult());
        sl.updateList();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSchedule = new javax.swing.JTable();
        btnAll = new javax.swing.JButton();
        btnOnce = new javax.swing.JButton();

        jLabel1.setText("Predict Result");

        tblSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Home", "Away", "HomeWinRate", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSchedule);

        btnAll.setText("Predict All");
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });

        btnOnce.setText("Predict Next Game");
        btnOnce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel1)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(btnOnce)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAll)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOnce)
                    .addComponent(btnAll))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
        // TODO add your handling code here:
        for (int i = sl.getFinishNum(); i < sl.getScheduleList().size(); i++) {
            Schedule s = sl.getScheduleList().get(i);
            sl.setFinishNum(i);
            runGame(s);
        }
        populateTable();
        reset = true;
        btnReset.setEnabled(reset);
        btnAll.setEnabled(!reset);
        btnOnce.setEnabled(!reset);
    }//GEN-LAST:event_btnAllActionPerformed

    private void btnOnceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnceActionPerformed
        // TODO add your handling code here:
        int n = sl.getFinishNum();
        Schedule s = sl.getScheduleList().get(n);
        btnOnce.setEnabled(!sl.checkFinish());
        btnReset.setEnabled(reset || sl.checkFinish());
        btnAll.setEnabled(!sl.checkFinish());
        sl.setFinishNum(++n);
        runGame(s);
        populateTable();
    }//GEN-LAST:event_btnOnceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAll;
    private javax.swing.JButton btnOnce;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSchedule;
    // End of variables declaration//GEN-END:variables
}
